file:
  path: '/app/data'
  topic:
    name: topic-file
    partitions: 1
    replications: 1
spring:
  kafka:
    bootstrap-servers: 'kafka:29092'
    consumer:
      group-id: group-file-id
      auto-offset-reset: earliest

